# Generated by Django 5.1.1 on 2024-09-17 10:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0002_player'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bet',
            old_name='predicted_away_score',
            new_name='away_score',
        ),
        migrations.RenameField(
            model_name='bet',
            old_name='predicted_home_score',
            new_name='home_score',
        ),
        migrations.AddField(
            model_name='bet',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bet',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bets.team'),
        ),
    ]
