# Generated by Django 5.1.1 on 2024-09-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bets', '0003_rename_predicted_away_score_bet_away_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
